export default {
  REGISTER_START: 'AUTH_REGISTER_START',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAIL: 'AUTH_REGISTER_FAIL',
  LOGIN_START: 'AUTH_LOGIN_START',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAIL: 'AUTH_LOGIN_FAIL'
}