export default {
  GET_ALL_START: 'DOCUMENTS_GET_ALL_START',
  GET_ALL_SUCCESS: 'DOCUMENTS_GET_ALL_SUCCESS',
  GET_ALL_FAIL: 'DOCUMENTS_GET_ALL_FAIL',
  GET_ONE_START: 'DOCUMENTS_GET_ONE_START',
  GET_ONE_SUCCESS: 'DOCUMENTS_GET_ONE_SUCCESS',
  GET_ONE_FAIL: 'DOCUMENTS_GET_ONE_FAIL',
  EDIT_ONE_START: 'DOCUMENTS_EDIT_ONE_START',
  EDIT_ONE_SUCCESS: 'DOCUMENTS_EDIT_ONE_SUCCESS',
  EDIT_ONE_FAIL: 'DOCUMENTS_EDIT_ONE_FAIL',
  SORT_A_Z: 'DOCUMENTS_SORT_A_Z',
  SORT_Z_A: 'DOCUMENTS_SORT_Z_A',
  SORT_DEFAULT: 'DOCUMENTS_SORT_DEFAULT'
}